 const ALCONPRICES =
 [
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix plus HydraGlyde",
     "nameID": "A001",
     "boxID": "06P",
     "image": "AirOptixHydraGlyde",
     "colorUpgrade": true,
     "featured": false,
     "schedule": "1M",
     "MSRP": 74.27,
     "list": 36.5
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix plus HydraGlyde for Astigmatism",
     "nameID": "A002",
     "boxID": "06P",
     "image": "AirOptixHydraGlydeT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 89.16,
     "list": 45.7
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix plus HydraGlyde Multifocal",
     "nameID": "A003",
     "boxID": "06P",
     "image": "AirOptixHydraGlydeMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 119.54,
     "list": 69.8
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix Colors",
     "nameID": "A004",
     "boxID": "02P",
     "image": "AirOptixColors",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 53.5,
     "list": 30.15
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix Colors",
     "nameID": "A004",
     "boxID": "06P",
     "image": "AirOptixColors",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 127.03,
     "list": 77.2
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix Night & Day Aqua",
     "nameID": "A005",
     "boxID": "06P",
     "image": "AirOptixNightAndDay",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 113.93,
     "list": 65.05
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus",
     "nameID": "A006",
     "boxID": "30P",
     "image": "DailiesAquaComfortPlus",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 43.31,
     "list": 18.95
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus",
     "nameID": "A006",
     "boxID": "90P",
     "image": "DailiesAquaComfortPlus",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 80.45,
     "list": 47.3
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus Multifocal",
     "nameID": "A007",
     "boxID": "30P",
     "image": "DailiesAquaComfortPlusT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 48.05,
     "list": 25.2
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus Multifocal",
     "nameID": "A007",
     "boxID": "90P",
     "image": "DailiesAquaComfortPlusT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 103.38,
     "list": 64.65
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus Toric",
     "nameID": "A008",
     "boxID": "30P",
     "image": "DailiesAquaComfortPlusMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 57.73,
     "list": 30.3
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus Toric",
     "nameID": "A008",
     "boxID": "90P",
     "image": "DailiesAquaComfortPlusMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 126.19,
     "list": 74.45
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Colors",
     "name": "Dailies Colors",
     "nameID": "A009",
     "boxID": "30P",
     "image": "DailiesColors",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 39.7,
     "list": 25.55
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Colors",
     "name": "Dailies Colors",
     "nameID": "A009",
     "boxID": "90P",
     "image": "DailiesColors",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 85.08,
     "list": 54.45
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1",
     "nameID": "A010",
     "boxID": "30P",
     "image": "DailiesTotal130",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 46.29,
     "list": 31
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1",
     "nameID": "A010",
     "boxID": "90P",
     "image": "DailiesTotal130",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 121.53,
     "list": 80.55
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1 for Astigmatism",
     "nameID": "A011",
     "boxID": "30P",
     "image": "DailiesTotal1T30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 57.85,
     "list": 36.85
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1 for Astigmatism",
     "nameID": "A011",
     "boxID": "90P",
     "image": "DailiesTotal1T30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 143.01,
     "list": 96.05
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1 Multifocal",
     "nameID": "A012",
     "boxID": "30P",
     "image": "DailiesTotal1MF30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 67.62,
     "list": 39.25
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1 Multifocal",
     "nameID": "A012",
     "boxID": "90P",
     "image": "DailiesTotal1MF30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 166.24,
     "list": 103.05
    },
    {
     "manuf": "Alcon",
     "brand": "Focus",
     "name": "Focus Dailies",
     "nameID": "A013",
     "boxID": "30P",
     "image": "FocusDailies30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 50.81,
     "list": 24.25
    },
    {
     "manuf": "Alcon",
     "brand": "Focus",
     "name": "Focus Dailies",
     "nameID": "A013",
     "boxID": "90P",
     "image": "FocusDailies30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 94.39,
     "list": 60.45
    },
    {
     "manuf": "Alcon",
     "brand": "Freshlook",
     "name": "Freshlook Colorblends",
     "nameID": "A014",
     "boxID": "06P",
     "image": "FreshlookColorblends",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 118.47,
     "list": 77.25
    },
    {
     "manuf": "Alcon",
     "brand": "Freshlook",
     "name": "Freshlook Handling Tint",
     "nameID": "A016",
     "boxID": "06P",
     "image": "FreshlookHandlingTint",
     "colorUpgrade": true,
     "featured": false,
     "schedule": "2W",
     "MSRP": 118.47,
     "list": 77.25
    },
    {
     "manuf": "Alcon",
     "brand": "Precision1",
     "name": "Precision1",
     "nameID": "A017",
     "boxID": "30P",
     "image": "Precision130",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 41.38,
     "list": 24.95
    },
    {
     "manuf": "Alcon",
     "brand": "Precision1",
     "name": "Precision1",
     "nameID": "A017",
     "boxID": "90P",
     "image": "Precision130",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 89.25,
     "list": 53.85
    },
    {
     "manuf": "Alcon",
     "brand": "Precision1",
     "name": "Precision1 for Astigmatism",
     "nameID": "A018",
     "boxID": "30P",
     "image": "Precision1T30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 57.18,
     "list": 31.55
    },
    {
     "manuf": "Alcon",
     "brand": "Precision1",
     "name": "Precision1 for Astigmatism",
     "nameID": "A018",
     "boxID": "90P",
     "image": "Precision1T30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 143.01,
     "list": 67.7
    },
    {
     "manuf": "Alcon",
     "brand": "Total30",
     "name": "Total30",
     "nameID": "A019",
     "boxID": "06P",
     "image": "Total30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 76.63,
     "list": 40.55
    },
    {
     "manuf": "Alcon",
     "brand": "Total30",
     "name": "Total30 for Astigmatism",
     "nameID": "A020",
     "boxID": "06P",
     "image": "Total30T",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 84,
     "list": 49
    }
   ]

    export default ALCONPRICES;