const BAUSCHPRICES =
[
    {
     "manuf": "Bausch + Lomb",
     "brand": "Infuse",
     "name": "Infuse One-Day",
     "nameID": "BL01",
     "boxID": "90P",
     "image": "Infuse",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 68.5,
     "MSRP": 108
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Infuse",
     "name": "Infuse One-Day Multifocal",
     "nameID": "BL02",
     "boxID": "90P",
     "image": "InfuseMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 78.01,
     "MSRP": 130
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday",
     "nameID": "BL03",
     "boxID": "30P",
     "image": "OneDay",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 26.01,
     "MSRP": 36
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday",
     "nameID": "BL03",
     "boxID": "90P",
     "image": "OneDay",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 49.5,
     "MSRP": 77
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday for Astigmatism",
     "nameID": "BL04",
     "boxID": "30P",
     "image": "OneDayT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 32.01,
     "MSRP": 47
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday for Astigmatism",
     "nameID": "BL04",
     "boxID": "90P",
     "image": "OneDayT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 61.5,
     "MSRP": 91
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday for Presbyopia",
     "nameID": "BL05",
     "boxID": "90P",
     "image": "OneDayP",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 37.01,
     "MSRP": 48
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday for Presbyopia",
     "nameID": "BL05",
     "boxID": "90P",
     "image": "OneDayP",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 71,
     "MSRP": 107
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Ultra",
     "name": "Ultra",
     "nameID": "BL06",
     "boxID": "06P",
     "image": "Ultra",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 35.5,
     "MSRP": 68
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Ultra",
     "name": "Ultra for Astigmatism",
     "nameID": "BL07",
     "boxID": "06P",
     "image": "UltraT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 45.5,
     "MSRP": 80
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Ultra",
     "name": "Ultra for Presbyopia",
     "nameID": "BL08",
     "boxID": "06P",
     "image": "UltraP",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 60,
     "MSRP": 96
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Ultra",
     "name": "Ultra Multifocal for Astigmatism",
     "nameID": "BL09",
     "boxID": "06P",
     "image": "UltraMFT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 90.5,
     "MSRP": 150
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision",
     "name": "PureVision",
     "nameID": "BL10",
     "boxID": "06P",
     "image": "PureVision",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 63,
     "MSRP": 97
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision",
     "name": "PureVision Multi-Focal",
     "nameID": "BL11",
     "boxID": "06P",
     "image": "PureVisionMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 68.5,
     "MSRP": 99
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision2",
     "name": "PureVision2",
     "nameID": "BL12",
     "boxID": "06P",
     "image": "PureVision2",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 52.5,
     "MSRP": 79
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision2",
     "name": "PureVision2 for Astigmatism",
     "nameID": "BL13",
     "boxID": "06P",
     "image": "PureVision2T",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 52.5,
     "MSRP": 80
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision2",
     "name": "PureVision2 For Presbyopia",
     "nameID": "BL14",
     "boxID": "06P",
     "image": "PureVision2MF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "list": 59,
     "MSRP": 94
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Soflens",
     "name": "Soflens 38",
     "nameID": "BL15",
     "boxID": "06P",
     "image": "Soflens38",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "list": 22,
     "MSRP": 36
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Soflens",
     "name": "Soflens Toric",
     "nameID": "BL16",
     "boxID": "06P",
     "image": "SoflensT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "list": 34,
     "MSRP": 58
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Soflens",
     "name": "Soflens Multi-Focal",
     "nameID": "BL17",
     "boxID": "06P",
     "image": "SoflensMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "list": 52,
     "MSRP": 80
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Soflens",
     "name": "Soflens daily disposable",
     "nameID": "BL18",
     "boxID": "90P",
     "image": "SoflensDailyDisposable30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "list": 45,
     "MSRP": 70
    }
   ]

   export default BAUSCHPRICES;