export const CONTACTLENSES = 
[
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys Max 1-Day",
     "nameID": "V001",
     "image": "OasysMax30",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.5, 9.0",
     "BC1": "8.5",
     "BC2": "9.0",
     "diam": 14.3
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys Max 1-Day Multifocal",
     "nameID": "V002",
     "image": "OasysMaxMF30",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": 14.3
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys 1-Day",
     "nameID": "V003",
     "image": "Oasys1D90",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.5, 9.0",
     "BC1": "8.5",
     "BC2": "9.0",
     "diam": 14.3
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys 1-Day for Astigmatism",
     "nameID": "V004",
     "image": "Oasys1DT90",
     "priceSix": 80,
     "priceYear": 160,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": 14.3
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist",
     "nameID": "V005",
     "image": "Moist90",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.5, 9.0",
     "BC1": "8.5",
     "BC2": "9.0",
     "diam": 14.2
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist for Astigmatism",
     "nameID": "V006",
     "image": "MoistT90",
     "priceSix": 110,
     "priceYear": 220,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": 14.5
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist Multifocal",
     "nameID": "V007",
     "image": "MoistMF90",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": 14.3
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys",
     "nameID": "V008",
     "image": "Oasys12",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.4, 8.8",
     "BC1": "8.4",
     "BC2": "8.8",
     "diam": "14.0"
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys for Astigmatism",
     "nameID": "V009",
     "image": "OasysT6",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys Multifocal",
     "nameID": "V010",
     "image": "OasysMF6",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": "14.3"
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys with Transitions",
     "nameID": "V012",
     "image": "OasysTr6",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": true,
     "multBC": true,
     "BC": "8.4, 8.8",
     "BC1": "8.4",
     "BC2": "8.8",
     "diam": "14.0"
    },
    {
     "manuf": "Acuvue",
     "brand": "Vita",
     "name": "Vita",
     "nameID": "V013",
     "image": "Vita",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.4, 8.8",
     "BC1": "8.4",
     "BC2": "8.8",
     "diam": "14.0"
    },
    {
     "manuf": "Acuvue",
     "brand": "Vita",
     "name": "Vita for Astigmatism",
     "nameID": "V014",
     "image": "VitaT",
     "priceSix": 80,
     "priceYear": 160,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    },
    {
     "manuf": "Acuvue",
     "brand": "Define",
     "name": "Define",
     "nameID": "V015",
     "image": "Define",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": true,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.2"
    },
    {
     "manuf": "Acuvue",
     "brand": "Acuvue2",
     "name": "Acuvue2",
     "nameID": "V017",
     "image": "Acuvue2",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.3, 8.7",
     "BC1": "8.3",
     "BC2": "8.7",
     "diam": "14.0"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Infuse",
     "name": "Infuse One-Day",
     "nameID": "BL01",
     "image": "Infuse",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Infuse",
     "name": "Infuse One-Day Multifocal",
     "nameID": "BL02",
     "image": "InfuseMF",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday",
     "nameID": "BL03",
     "image": "OneDay",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday for Astigmatism",
     "nameID": "BL04",
     "image": "OneDayT",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": "14.5"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Biotrue",
     "name": "ONEday for Presbyopia",
     "nameID": "BL05",
     "image": "OneDayP",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Ultra",
     "name": "Ultra",
     "nameID": "BL06",
     "image": "Ultra",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.2"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Ultra",
     "name": "Ultra for Astigmatism",
     "nameID": "BL07",
     "image": "UltraT",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Ultra",
     "name": "Ultra for Presbyopia",
     "nameID": "BL08",
     "image": "UltraP",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.2"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Ultra",
     "name": "Ultra Multifocal for Astigmatism",
     "nameID": "BL09",
     "image": "UltraMFT",
     "priceSix": 80,
     "priceYear": 160,
     "toric": true,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision",
     "name": "PureVision",
     "nameID": "BL10",
     "image": "PureVision",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.3, 8.6",
     "BC1": "8.3",
     "BC2": "8.6",
     "diam": "14.0"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision",
     "name": "PureVision Multi-Focal",
     "nameID": "BL11",
     "image": "PureVisionMF",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.0"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision2",
     "name": "PureVision2",
     "nameID": "BL12",
     "image": "PureVision2",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.0"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision2",
     "name": "PureVision2 for Astigmatism",
     "nameID": "BL13",
     "image": "PureVision2T",
     "priceSix": 80,
     "priceYear": 160,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.5"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "PureVision2",
     "name": "PureVision2 For Presbyopia",
     "nameID": "BL14",
     "image": "PureVision2MF",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.0"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Soflens",
     "name": "Soflens 38",
     "nameID": "BL15",
     "image": "Soflens38",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.4, 8.7, 9.0",
     "BC1": "8.4",
     "BC2": "8.7",
     "BC3": "9.0",
     "diam": "14.0"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Soflens",
     "name": "Soflens Toric",
     "nameID": "BL16",
     "image": "SoflensT",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.5"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Soflens",
     "name": "Soflens Multi-Focal",
     "nameID": "BL17",
     "image": "SoflensMF",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": true,
     "BC": "8.5, 8.8",
     "BC1": "8.5",
     "BC2": "8.8",
     "diam": "14.5"
    },
    {
     "manuf": "Bausch + Lomb",
     "brand": "Soflens",
     "name": "Soflens daily disposable",
     "nameID": "BL18",
     "image": "SoflensDailyDisposable30",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "Avaira Vitality",
     "name": "Avaira Vitality",
     "nameID": "CV01",
     "image": "AvairaVitality",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "Avaira Vitality",
     "name": "Avaira Vitality toric",
     "nameID": "CV02",
     "image": "AvairaVitalityT",
     "priceSix": 80,
     "priceYear": 160,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.5"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity",
     "nameID": "CV03",
     "image": "Biofinity",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.0"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity XR",
     "nameID": "CV04",
     "image": "Biofinity",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.0"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity Energys",
     "nameID": "CV05",
     "image": "BiofinityEnergys",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.0"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity multifocal",
     "nameID": "CV06",
     "image": "BiofinityMF",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.0"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity toric",
     "nameID": "CV07",
     "image": "BiofinityT",
     "priceSix": 110,
     "priceYear": 220,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.5"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity XR toric",
     "nameID": "CV08",
     "image": "BiofinityT",
     "priceSix": 80,
     "priceYear": 160,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.5"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity toric multifocal",
     "nameID": "CV09",
     "image": "BiofinityTMF",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.5"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biomedics",
     "name": "Biomedics 55 Premier asphere",
     "nameID": "CV10",
     "image": "Biomedics55Premier",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "Biomedics",
     "name": "Biomedics Toric",
     "nameID": "CV11",
     "image": "BiomedicsT",
     "priceSix": 80,
     "priceYear": 160,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.5"
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day",
     "nameID": "CV12",
     "image": "Clariti1day",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.1"
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day toric",
     "nameID": "CV13",
     "image": "Clariti1dayT",
     "priceSix": 110,
     "priceYear": 220,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.3"
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day multifocal",
     "nameID": "CV14",
     "image": "Clariti1dayMF",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.1"
    },
    {
     "manuf": "CooperVision",
     "brand": "MiSight",
     "name": "MiSight 1 day",
     "nameID": "CV15",
     "image": "MiSight1day",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "MyDay",
     "name": "MyDay",
     "nameID": "CV16",
     "image": "MyDay",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "MyDay",
     "name": "MyDay Energys",
     "nameID": "CV17",
     "image": "MyDayEnergys",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "MyDay",
     "name": "MyDay multifocal",
     "nameID": "CV18",
     "image": "MyDayMF",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "MyDay",
     "name": "MyDay toric",
     "nameID": "CV19",
     "image": "MyDayT",
     "priceSix": 110,
     "priceYear": 220,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear 1 day",
     "nameID": "CV20",
     "image": "Proclear1day",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear 1 day multifocal",
     "nameID": "CV21",
     "image": "Proclear1dayMF",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear multifocal",
     "nameID": "CV22",
     "image": "ProclearMF",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.4"
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear multifocal XR",
     "nameID": "CV23",
     "image": "ProclearMF",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": true,
     "BC": "8.4, 8.7",
     "BC1": "8.4",
     "BC2": "8.7",
     "diam": "14.4"
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear multifocal toric",
     "nameID": "CV24",
     "image": "ProclearMFT",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": true,
     "color": false,
     "multBC": true,
     "BC": "8.4, 8.8",
     "BC1": "8.4",
     "BC2": "8.8",
     "diam": "14.4"
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear sphere",
     "nameID": "CV25",
     "image": "Proclear",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.2, 8.6",
     "BC1": "8.2",
     "BC2": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear toric",
     "nameID": "CV26",
     "image": "ProclearT",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.4, 8.8",
     "BC1": "8.4",
     "BC2": "8.8",
     "diam": "14.4"
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear toric XR",
     "nameID": "CV27",
     "image": "ProclearT",
     "priceSix": 110,
     "priceYear": 220,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.4, 8.8",
     "BC1": "8.4",
     "BC2": "8.8",
     "diam": "14.4"
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix plus HydraGlyde",
     "nameID": "A001",
     "image": "AirOptixHydraGlyde",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix plus HydraGlyde for Astigmatism",
     "nameID": "A002",
     "image": "AirOptixHydraGlydeT",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.5"
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix plus HydraGlyde Multifocal",
     "nameID": "A003",
     "image": "AirOptixHydraGlydeMF",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix Colors",
     "nameID": "A004",
     "image": "AirOptixColors",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": true,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.2"
    },
    {
     "manuf": "Alcon",
     "brand": "Air Optix",
     "name": "Air Optix Night & Day Aqua",
     "nameID": "A005",
     "image": "AirOptixNightAndDay",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": true,
     "BC": "8.4, 8.6",
     "BC1": "8.4",
     "BC2": "8.6",
     "diam": "13.8"
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus",
     "nameID": "A006",
     "image": "DailiesAquaComfortPlus",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.0"
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus Multifocal",
     "nameID": "A007",
     "image": "DailiesAquaComfortPlusT",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.8",
     "BC1": "8.8",
     "diam": "14.4"
    },
    {
     "manuf": "Alcon",
     "brand": "DailiesACP",
     "name": "Dailies AquaComfort Plus Toric",
     "nameID": "A008",
     "image": "DailiesAquaComfortPlusMF",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.7",
     "BC1": "8.7",
     "diam": "14.0"
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Colors",
     "name": "Dailies Colors",
     "nameID": "A009",
     "image": "DailiesColors",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": true,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "13.8"
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1",
     "nameID": "A010",
     "image": "DailiesTotal130",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.1"
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1 for Astigmatism",
     "nameID": "A011",
     "image": "DailiesTotal1T30",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    },
    {
     "manuf": "Alcon",
     "brand": "Dailies Total 1",
     "name": "Dailies Total 1 Multifocal",
     "nameID": "A012",
     "image": "DailiesTotal1MF30",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": true,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.1"
    },
    {
     "manuf": "Alcon",
     "brand": "Focus",
     "name": "Focus Dailies",
     "nameID": "A013",
     "image": "FocusDailies30",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "13.8"
    },
    {
     "manuf": "Alcon",
     "brand": "Freshlook",
     "name": "Freshlook Colorblends",
     "nameID": "A014",
     "image": "FreshlookColorblends",
     "priceSix": 120,
     "priceYear": 240,
     "toric": false,
     "multifocal": false,
     "color": true,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    },
    {
     "manuf": "Alcon",
     "brand": "Freshlook",
     "name": "Freshlook Handling Tint",
     "nameID": "A016",
     "image": "FreshlookHandlingTint",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    },
    {
     "manuf": "Alcon",
     "brand": "Precision1",
     "name": "Precision1",
     "nameID": "A017",
     "image": "Precision130",
     "priceSix": 80,
     "priceYear": 160,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.3",
     "BC1": "8.3",
     "diam": "14.2"
    },
    {
     "manuf": "Alcon",
     "brand": "Precision1",
     "name": "Precision1 for Astigmatism",
     "nameID": "A018",
     "image": "Precision1T30",
     "priceSix": 120,
     "priceYear": 240,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.5",
     "BC1": "8.5",
     "diam": "14.5"
    },
    {
     "manuf": "Alcon",
     "brand": "Total30",
     "name": "Total30",
     "nameID": "A019",
     "image": "Total30",
     "priceSix": 110,
     "priceYear": 220,
     "toric": false,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.4",
     "BC1": "8.4",
     "diam": "14.2"
    },
    {
     "manuf": "Alcon",
     "brand": "Total30",
     "name": "Total30 for Astigmatism",
     "nameID": "A020",
     "image": "Total30T",
     "priceSix": 80,
     "priceYear": 120,
     "toric": true,
     "multifocal": false,
     "color": false,
     "multBC": false,
     "BC": "8.6",
     "BC1": "8.6",
     "diam": "14.5"
    }
   ]