const COOPERPRICES =
[
    {
     "manuf": "CooperVision",
     "brand": "Avaira Vitality",
     "name": "Avaira Vitality",
     "nameID": "CV01",
     "boxID": "06P",
     "image": "AvairaVitality",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 39,
     "list": 17
    },
    {
     "manuf": "CooperVision",
     "brand": "Avaira Vitality",
     "name": "Avaira Vitality toric",
     "nameID": "CV02",
     "boxID": "06P",
     "image": "AvairaVitalityT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 42,
     "list": 24
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity",
     "nameID": "CV03",
     "boxID": "06P",
     "image": "Biofinity",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 55,
     "list": 28
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity XR",
     "nameID": "CV04",
     "boxID": "06P",
     "image": "Biofinity",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 55,
     "list": 28
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity Energys",
     "nameID": "CV05",
     "boxID": "06P",
     "image": "BiofinityEnergys",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 62,
     "list": 33
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity multifocal",
     "nameID": "CV06",
     "boxID": "06P",
     "image": "BiofinityMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 87,
     "list": 53
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity toric",
     "nameID": "CV07",
     "boxID": "06P",
     "image": "BiofinityT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 75,
     "list": 41
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity XR toric",
     "nameID": "CV08",
     "boxID": "06P",
     "image": "BiofinityT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 147,
     "list": 88
    },
    {
     "manuf": "CooperVision",
     "brand": "Biofinity",
     "name": "Biofinity toric multifocal",
     "nameID": "CV09",
     "boxID": "06P",
     "image": "BiofinityTMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 160,
     "list": 112
    },
    {
     "manuf": "CooperVision",
     "brand": "Biomedics",
     "name": "Biomedics 55 Premier asphere",
     "nameID": "CV10",
     "boxID": "06P",
     "image": "Biomedics55Premier",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 45,
     "list": 21
    },
    {
     "manuf": "CooperVision",
     "brand": "Biomedics",
     "name": "Biomedics Toric",
     "nameID": "CV11",
     "boxID": "06P",
     "image": "BiomedicsT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 52,
     "list": 25
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day",
     "nameID": "CV12",
     "boxID": "30P",
     "image": "Clariti1day",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 38,
     "list": 25
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day",
     "nameID": "CV12",
     "boxID": "90P",
     "image": "Clariti1day",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 75,
     "list": 40
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day toric",
     "nameID": "CV13",
     "boxID": "30P",
     "image": "Clariti1dayT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 52,
     "list": 35
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day toric",
     "nameID": "CV13",
     "boxID": "90P",
     "image": "Clariti1dayT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 85,
     "list": 50
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day multifocal",
     "nameID": "CV14",
     "boxID": "30P",
     "image": "Clariti1dayMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 65,
     "list": 40
    },
    {
     "manuf": "CooperVision",
     "brand": "Clariti",
     "name": "clariti 1 day multifocal",
     "nameID": "CV14",
     "boxID": "90P",
     "image": "Clariti1dayMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 95,
     "list": 58
    },
    {
     "manuf": "CooperVision",
     "brand": "MiSight",
     "name": "MiSight 1 day",
     "nameID": "CV15",
     "boxID": "90P",
     "image": "MiSight1day",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 888,
     "list": 555
    },
    {
     "manuf": "CooperVision",
     "brand": "MyDay",
     "name": "MyDay",
     "nameID": "CV16",
     "boxID": "90P",
     "image": "MyDay",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 84,
     "list": 51
    },
    {
     "manuf": "CooperVision",
     "brand": "MyDay",
     "name": "MyDay Energys",
     "nameID": "CV17",
     "boxID": "90P",
     "image": "MyDayEnergys",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 125,
     "list": 76
    },
    {
     "manuf": "CooperVision",
     "brand": "MyDay",
     "name": "MyDay multifocal",
     "nameID": "CV18",
     "boxID": "90P",
     "image": "MyDayMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 145,
     "list": 95
    },
    {
     "manuf": "CooperVision",
     "brand": "MyDay",
     "name": "MyDay toric",
     "nameID": "CV19",
     "boxID": "90P",
     "image": "MyDayT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 100,
     "list": 64
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear 1 day",
     "nameID": "CV20",
     "boxID": "90P",
     "image": "Proclear1day",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 75,
     "list": 46
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear 1 day multifocal",
     "nameID": "CV21",
     "boxID": "90P",
     "image": "Proclear1dayMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 102,
     "list": 71
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear multifocal",
     "nameID": "CV22",
     "boxID": "06P",
     "image": "ProclearMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 105,
     "list": 69
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear multifocal XR",
     "nameID": "CV23",
     "boxID": "06P",
     "image": "ProclearMF",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 180,
     "list": 110
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear multifocal toric",
     "nameID": "CV24",
     "boxID": "06P",
     "image": "ProclearMFT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 179,
     "list": 125
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear sphere",
     "nameID": "CV25",
     "boxID": "06P",
     "image": "Proclear",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 65,
     "list": 40
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear toric",
     "nameID": "CV26",
     "boxID": "06P",
     "image": "ProclearT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 98,
     "list": 54
    },
    {
     "manuf": "CooperVision",
     "brand": "Proclear",
     "name": "Proclear toric XR",
     "nameID": "CV27",
     "boxID": "06P",
     "image": "ProclearT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 172,
     "list": 94
    }
   ]

   export default COOPERPRICES;