const VISTAKONPRICES = [
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys Max 1-Day",
     "nameID": "V001",
     "boxID": "30P",
     "image": "OasysMax30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 56.03,
     "list": 39.64
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys Max 1-Day",
     "nameID": "V001",
     "boxID": "90P",
     "image": "OasysMax30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 124.5,
     "list": 88.08
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys Max 1-Day Multifocal",
     "nameID": "V002",
     "boxID": "30P",
     "image": "OasysMaxMF30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 72.47,
     "list": 48.84
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys Max 1-Day Multifocal",
     "nameID": "V002",
     "boxID": "90P",
     "image": "OasysMaxMF30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 162.3,
     "list": 109.37
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys 1-Day",
     "nameID": "V003",
     "boxID": "90P",
     "image": "Oasys1D90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 110.25,
     "list": 76
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys 1-Day for Astigmatism",
     "nameID": "V004",
     "boxID": "30P",
     "image": "Oasys1DT90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 57.5,
     "list": 40.25
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys 1-Day for Astigmatism",
     "nameID": "V004",
     "boxID": "90P",
     "image": "Oasys1DT90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 131,
     "list": 95.5
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist",
     "nameID": "V005",
     "boxID": "30P",
     "image": "Moist90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 44.25,
     "list": 27
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist",
     "nameID": "V005",
     "boxID": "90P",
     "image": "Moist90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 82.5,
     "list": 50.25
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist for Astigmatism",
     "nameID": "V006",
     "boxID": "30P",
     "image": "MoistT90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 48.25,
     "list": 33.75
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist for Astigmatism",
     "nameID": "V006",
     "boxID": "90P",
     "image": "MoistT90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 105.5,
     "list": 74.5
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist Multifocal",
     "nameID": "V007",
     "boxID": "30P",
     "image": "MoistMF90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 64,
     "list": 43.75
    },
    {
     "manuf": "Acuvue",
     "brand": "Moist",
     "name": "Moist Multifocal",
     "nameID": "V007",
     "boxID": "90P",
     "image": "MoistMF90",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 119.5,
     "list": 81.75
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys",
     "nameID": "V008",
     "boxID": "12P",
     "image": "Oasys12",
     "colorUpgrade": true,
     "featured": false,
     "schedule": "2W",
     "MSRP": 103.25,
     "list": 59.25
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys",
     "nameID": "V008",
     "boxID": "24P",
     "image": "Oasys12",
     "colorUpgrade": true,
     "featured": false,
     "schedule": "2W",
     "MSRP": 155,
     "list": 86.5
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys for Astigmatism",
     "nameID": "V009",
     "boxID": "06P",
     "image": "OasysT6",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 57.25,
     "list": 32.5
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys Multifocal",
     "nameID": "V010",
     "boxID": "06P",
     "image": "OasysMF6",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 54.5,
     "list": 33.75
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys with Transitions",
     "nameID": "V012",
     "boxID": "06P",
     "image": "OasysTr6",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 57.5,
     "list": 34.75
    },
    {
     "manuf": "Acuvue",
     "brand": "Oasys",
     "name": "Oasys with Transitions",
     "nameID": "V012",
     "boxID": "25P",
     "image": "OasysTr6",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 209,
     "list": 133.25
    },
    {
     "manuf": "Acuvue",
     "brand": "Vita",
     "name": "Vita",
     "nameID": "V013",
     "boxID": "06P",
     "image": "Vita",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 82,
     "list": 48.5
    },
    {
     "manuf": "Acuvue",
     "brand": "Vita",
     "name": "Vita",
     "nameID": "V013",
     "boxID": "12P",
     "image": "Vita",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 131,
     "list": 69.75
    },
    {
     "manuf": "Acuvue",
     "brand": "Vita",
     "name": "Vita for Astigmatism",
     "nameID": "V014",
     "boxID": "06P",
     "image": "VitaT",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "1M",
     "MSRP": 85.25,
     "list": 44.5
    },
    {
     "manuf": "Acuvue",
     "brand": "Define",
     "name": "Define",
     "nameID": "V015",
     "boxID": "30P",
     "image": "Define",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 42.75,
     "list": 27.75
    },
    {
     "manuf": "Acuvue",
     "brand": "TruEye",
     "name": "TruEye",
     "nameID": "V016",
     "boxID": "30P",
     "image": "TruEye30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 70.25,
     "list": 48
    },
    {
     "manuf": "Acuvue",
     "brand": "TruEye",
     "name": "TruEye",
     "nameID": "V016",
     "boxID": "90P",
     "image": "TruEye30",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "DD",
     "MSRP": 134.75,
     "list": 92.5
    },
    {
     "manuf": "Acuvue",
     "brand": "Acuvue2",
     "name": "Acuvue2",
     "nameID": "V017",
     "boxID": "06P",
     "image": "Acuvue2",
     "colorUpgrade": false,
     "featured": false,
     "schedule": "2W",
     "MSRP": 42,
     "list": 27
    }
   ]

export default VISTAKONPRICES;